### ISSUE TITLE
Scripts doesn't work after a System Reset.

### ISSUE THREAD

**Issue by Shnxxx** [Nuihc88/SVPlite#2]
Hi! it's me again! I cleaned my PC and did a full reset to it.
Right now, only few apps are currently installed and nothing is installed yet anything video-related apps except AviSynth+, LAVFilters, MadVR, and PotPlayer x64.

I have configured my PotPlayer already. Here they are:

![image](https://user-images.githubusercontent.com/48496678/100643078-92613880-3374-11eb-9300-8ef257b5d0b1.png)

![image](https://user-images.githubusercontent.com/48496678/100643116-9beaa080-3374-11eb-85a1-334708298ed8.png)

![image](https://user-images.githubusercontent.com/48496678/100643223-bb81c900-3374-11eb-9a48-acef1d5f9f2d.png)

(Everything here is checked)
![image](https://user-images.githubusercontent.com/48496678/100643434-fc79dd80-3374-11eb-8cc9-06a0e38503f0.png)

![image](https://user-images.githubusercontent.com/48496678/100643282-ce949900-3374-11eb-8c48-a7fd366575c9.png)

![image](https://user-images.githubusercontent.com/48496678/100643754-6befcd00-3375-11eb-8010-858a3406cc3f.png)

![image](https://user-images.githubusercontent.com/48496678/100643781-75793500-3375-11eb-94b5-fcbb010b16b9.png)

![image](https://user-images.githubusercontent.com/48496678/100643818-8164f700-3375-11eb-88d4-563e30432a88.png)

![image](https://user-images.githubusercontent.com/48496678/100643847-8b86f580-3375-11eb-9b0f-79877856ae43.png)

SVPFlow x64 and x32 `C:\Program Files\DAUM\PotPlayer\AviSynth\plugins`
Scripts : `C:\Program Files\DAUM\PotPlayer\AviSynth`
AviSynth : `C:\Program Files\DAUM\PotPlayer` and `C:\Windows\System32`

Am I missing something?
I also tried installing CrendKing's filter but it won't let me install it. I'm getting errors. Anw, Thank you!

**Comment by Nuihc88** [comment]
If you want to use PotPlayer's internal AviSynth filtering, you need to enable Video Transform Filter. However it's much slower than either of the external alternatives and i wouldn't recommend using either it or the transform filter.

To get CrendKing's AviSynth filter to load without having to install it in the system, you can the select it's .ax file directly from 'Preferences > Filter Control > Filter Priority > Add external filter...', then tick the box & set 'Prefer'.

**Comment by Shnxxx** [comment]
You mentioned that if I want to use PotPlayers AviSynth. Is there a way where I could use external AviSynth? I thought I am already using the AviSynth+? I already installed the AviSynth+ but I don't know if I'm using it already or not.

EDIT: I tried to enable `Transform Filter Usage` under `Filter Control` by switching it to `Always Use`, but still the filters won't work.

I did try `Add external filter` but after selecting it, it doesn't appear on the list.  Anw, you shouldn't problem it. I already opened an issue in CrendKing's git. Thank you again!

**Comment by Nuihc88** [comment]
>You mentioned that if I want to use PotPlayers AviSynth. Is there a way where I could use external AviSynth? I thought I am already using the AviSynth+? I already installed the AviSynth+ but I don't know if I'm using it already or not.

I just meant that if you are trying to load the script directly through PotPlayer (as in the screenshot above), you will need to have internal 'Video Transform Filter' set to 'Always Use' before 'Preferences > Video > AviSynth > Enable AviSynth processing' takes effect.
When it comes to AviSynth version, DirectShow-filters are mostly version agnostic, main difference being that some functions are missing in older and non-plus versions. Thus most user interfaces just refer to all versions (Plus, MinMod, MT, Neo) colloquially as AviSynth.

Note that once you get CrendKing's AviSynth filter loading into the list, at first you will need to access it's GUI from 'Preferences > Filter Control > Filter Priority > Filter Information' to point it to a script. Then uncomment '#AvsFilterSource()' line in 'SVPlite_Environment.avsi' to get the filter to load into Player's Filter Graph.

PS. Adding LAV Filters from 'Filter Priority' should be redundant when they're already selected from Source/Splitter & Decoder tabs. Also without setting 'Priority' to 'Prefer', it's unlikely these entries would do anything anyways.

**Comment by Shnxxx** [comment]
> you will need to have internal 'Video Transform Filter' set to 'Always Use' before 'Preferences > Video > AviSynth > Enable AviSynth processing' takes effect.
I tried this but still didn't work. I already switched to `Always Use` then enabled `AviSynth Processing`. I also switched rendered from MadVR to EVR just to check if frames are getting doubled. Because leaving MadVR enabled reports 60~ FPS but it does not really do frame interpolation.

I also removed the LAV Filters under `Filter Priority` as you suggest.

EDIT:
I did reset PotPlayer's configurations and just enabled `AviSynth Processing`,  `Add "potplayer_source()"`, and chose SVPlite_Light_Animated", still, they didn't work. 

EDIT2:
I reinstalled PotPlayer and did the same thing mentioned above, nothing changed. I think I am missing something. 

`AviSynth.dll` > `C:\Program Files\DAUM\PotPlayer`
`AviSynth.dll` > `C:\Windows\System32`
AviSynth Filters > `C:\Program Files\DAUM\PotPlayer\AviSynth`
`SVPFlow1.dll`, `SVPFlow1_64.dll`, `SVPFlow2.dll`, and `SVPFlow2_64.dll` > C:\Program Files\DAUM\PotPlayer\AviSynth\plugins
`SVPFlow1.dll`, and `SVPFlow2.dll` > C:\Program Files\DAUM\PotPlayer\AviSynth\plugins\x32
`SVPFlow1_64.dll`, and `SVPFlow2_64.dll` > C:\Program Files\DAUM\PotPlayer\AviSynth\plugins\x64

**Comment by Nuihc88** [comment]
You don't need to add both x32 & x64 versions as PotPlayer will only load one set; so 64bit .dlls for 64bit PotPlayer, etc.
Also my scripts assume the filter directory to be 'PlayerDirectory\AviSynth\plugins\', so 'PlayerDirectory\AviSynth\plugins\x64' won't even be checked. The filter name should also remain SVPflow.dll regardless of whether it's 64bit.

That said i have no idea what could be going wrong with enabling PotPlayer's internal AviSynth interface as AviSynth.dll is supposed to give an error if there is an issue with any of the filters...
I recommend double-checking that you have added 64bit .dlls to 64bit programs and vice versa, starting with AviSynth.dll in PotPlayer's directory.

**Comment by Shnxxx** [comment]
I got progress now. I got CrendKing's filter working now, it turns out that I am missing some runtime libraries.

Then I disabled `Built-in video transform filter` and everything below it.
Added `CrendKing's AviSynth filter` in the `Filter Priority (Overall)` as `Prefer`. 
Clicked `Filter Information...`, checked all `Input Formats` and browed for `SVPlite_Medium_Animated.avs`
Tried playing a video and an error showed up.
![image](https://user-images.githubusercontent.com/48496678/100953764-305c2b00-354e-11eb-8731-a5e7988465dd.png)

Btw, I am using now a PotPlayer x86. I was just doing some trial and error earlier but I got it working on it. If everything becomes successful, I'll try doing it on an x64.

Also, I used `ffdshow raw video filter` as `prefer` under `Filter Priority (Overall)` and disabled `LAV Filters` for awhile.

**Comment by Shnxxx** [comment]
>![image](https://user-images.githubusercontent.com/48496678/100954310-46b6b680-354f-11eb-9df6-731327a6ce68.png)


I think I know now what is this. I should create another `AviSynth` folder under `AviSynth`

After doing fixes from the previous issue (because SVSuper problem shows up again)
>First try uncommenting third line of `SVPlite_Processing.avsi`, so that `#clip=last` becomes `clip=last`.
Another problem pops up and this time I don't know how to fix it.
![image](https://user-images.githubusercontent.com/48496678/100954808-4539be00-3550-11eb-9429-bcfecab6e62f.png)

Also, I am getting weird blending. (This is the Crunchyroll's intro)
![image](https://user-images.githubusercontent.com/48496678/100954861-64385000-3550-11eb-8292-06da75496271.png)

Is it because of `CrendKing's AviSynth filter`?

**Comment by Nuihc88** [comment]
That combination of symptoms would suggest that you have both ffdshow's AviSynth filtering and CrendKing's AviSynth filtering enabled at the same time. Unless you are using ffdshow for something else, i recommend disabling it as it's outdated and can cause problems with other directshow-filters. If you need ffdshow for something, just disable ffdshow's AviSynth filtering from it's regular interface when using any other AviSynth loading interface. 

That extra 'AviSynth/' folder in the error is due to an inconsistency in how ffdshow sets the working directory differently depending on whether you load the script from a file or copy-paste the text to it directly.

The 'invalid arguments' error is due to 'SVSuper' not receiving a clip from ffdshow since it's 'ffdshow_source()' is not set. You won't need to worry about this once you disable ffdshow's redundant AviSynth instance.

The weird blending is due to CrendKing's filter processing the output (including the error) from ffdshow as if it were just any regular frames to be interpolated. In other words, CrendKing's filter is running correctly in the screenshot above.

**Comment by Shnxxx** [comment]
I removed ffdshow now but it keeps showing the `AviSynth/` folder error. Anw, I still created the folder and move files 1 by 1 until the folder error disappeared.

After doing all of that, a new error shows up which I don't know how to fix. I tried using the built-in AviSynth thinking that it might be `CrendKing's filter` causing the problem but unfortunately, the error is still there:
![image](https://user-images.githubusercontent.com/48496678/101147611-94b6e180-3657-11eb-96c2-f721455cd454.png)

Here are my current Filter settings now:
![image](https://user-images.githubusercontent.com/48496678/101147857-de073100-3657-11eb-8578-59893a500cf7.png)

They are both set to `Prefer`. My `Filter Priority (Preset-specific)` is empty. 
![image](https://user-images.githubusercontent.com/48496678/101147889-e9f2f300-3657-11eb-84c2-db7308971d7f.png)

Thank you again for your time!

**Comment by Nuihc88** [comment]
> I removed ffdshow now but it keeps showing the `AviSynth/` folder error. Anw, I still created the folder and move files 1 by 1 until the folder error disappeared.

Ok, i guess i was wrong, it's ffdshow that was processing CrendKing's filter output...

I made a patch to SVPlite_Processing.avsi in order to work around the 'Clip must be YV12' issue without user intervention being needed in the future.

I will need to take another look in the future at how to best handle PotPlayer/ffdshow/CrendKing's Avisynth-filtering support simultaneously, if it can be done without user intervention at all. **PS.** Looks like PotPlayer doesn't support AviSynth's ScriptDir() function so creating a reliable automatic working directory detection is going to be difficult.

**Comment by Shnxxx** [comment]
Thank you again for your reply!
`Clip must be YV12` issue was gone but a new error shows up.
![image](https://user-images.githubusercontent.com/48496678/101267406-44dd3500-3793-11eb-84d0-5c97d3ac928a.png)

I am using CrendKing's filter. I also disabled `Built-in Video Transform Filter` settings.
I tried using the built-in AviSynth and your script works perfectly fine. The problem occurs when CrendKing's AviSynth filter is being used.

**Comment by Nuihc88** [comment]
Took me a while to figure out what is likely going on...
Try uncommenting '#AvsFilterSource()' line in 'SVPlite_Environment.avsi'.
My guess is that you overwrote the earlier change to it at some point...

If that doesn't work, you can comment out the first Prefetch line, as it only provides a small performance boost under heavy loads.

**Comment by Shnxxx** [comment]
It is working now! but not quite. Uncommenting `#AvsFilterSource()` fixed the problem and no more error showed up. But, I observed that the FPS is not being doubled.
![image](https://user-images.githubusercontent.com/48496678/101299539-8b9f5d80-386d-11eb-8ad9-f48493dc7ac9.png)
As you can see here, it is higher than the input but only a few frames only. And as the video goes on, it keeps dropping frames.
I tried modifying `smoothfps_params` , changing `num:2,den:1` to `num:60000,den:1001,abs:true` didn't seem to work.

**Comment by Nuihc88** [comment]
Most of PotPlayer's metrics have never been very accurate even without frame interpolation...

To get accurate metrics you can use MadVR's ctrl+J ...or just to double-check that frame interpolation is taking place, you can also go to the Filter Graph at 'Right-Click menu > Filters >' and then to AviSynth Filter's Status-tab.

**Comment by Shnxxx** [comment]
Thank you again for your help! I checked it through MadVR's `Ctrl+J` and it shows there the correct FPS.

One more thing, when I use the `SVPLite_Medium_Animated`, it causes unsynced A/V, but everything is smooth. The video is late. When I used the `SVPLite_Light_Animated` A/V are synced but it causes frames to distort like this one :
![image](https://user-images.githubusercontent.com/48496678/101309491-8818d000-3887-11eb-94a7-cbfef9953d5e.png)

The `SVPLite_Medium_Animated` works fine without CrendKing's filter. Is there a way where I could use `SVPLite_Medium_Animated` without the A/V getting unsynced? or `SVPLite_Light_Animated` without those frames distorting?

I have NVIDIA MX150 with 2GB RAM, is my GPU is not powerful enough?

**Comment by Nuihc88** [comment]
Little bit of distortion in high motion scenes is normal when using frame interpolation and everyone has their own preferences when it comes to the trade-off between distortion & smoothness. However, i'm not sure why 'Light' settings would cause more of it than 'Medium' settings as the only things different between them are 'sort' 'trymany' & both of the 'distance' settings...
You could try checking if changing one of those will reduce distortion. Let me know if you figure it out as i may change the defaults if i can reproduce the issue.

Loss of A/V sync could be due to lack of processing power on either CPU or GPU, but more likely it's due to non-optimal settings in MadVR. You can try going through [my suggested settings here](https://github.com/Nuihc88/SVPlite/tree/master/ConfigRecommendations). However not everything there will necessarily be optimal for your computer; still i recommend at least setting all of MadVR's buffers to 16.

The folder also contains 'AviSynth_Filter_Tweak.reg' file, which contains two registry tweaks:
One of which ("Formats"=dword:00000002) potentially trades quality for speed,
while the other ("OutputThreads"=dword:00000002) just improves buffering performance.
